@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Dec 13 17:14:09 +0100 2025
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim DataPath_tb_behav -key {Behavioral:sim_1:Functional:DataPath_tb} -tclbatch DataPath_tb.tcl -view C:/Users/seppe/Documents/GitHub/Comar_assignment_4/RISCV_SUBLAB3/DataPath_tb_behav.wcfg -log simulate.log"
call xsim  DataPath_tb_behav -key {Behavioral:sim_1:Functional:DataPath_tb} -tclbatch DataPath_tb.tcl -view C:/Users/seppe/Documents/GitHub/Comar_assignment_4/RISCV_SUBLAB3/DataPath_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
